# Generated by Django 5.2.5 on 2025-08-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mb_included', models.IntegerField(help_text='Data limit in MB')),
                ('mb_price', models.DecimalField(decimal_places=4, help_text='Price per MB over limit', max_digits=10)),
                ('minute_price', models.DecimalField(decimal_places=4, help_text='Price per minute', max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mb_used', models.IntegerField(default=0)),
                ('minutes_used', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtrim_api.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtrim_api.plan'),
        ),
        migrations.CreateModel(
            name='PlanClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtrim_api.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtrim_api.plan')),
            ],
        ),
    ]
