# Generated by Django 5.2.5 on 2025-08-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtrim_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='consumption',
            table='consumptions',
        ),
        migrations.AlterModelTable(
            name='consumptiontype',
            table='consumption_types',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plans',
        ),
        migrations.AlterModelTable(
            name='planclient',
            table='plan_client',
        ),
    ]
