# Generated by Django 5.2.5 on 2025-08-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtrim_api', '0003_client_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='minutes_included',
            field=models.IntegerField(default=0, help_text='Minutes limit'),
        ),
    ]
